# Generated by Django 6.0 on 2026-01-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="status",
        ),
    ]
