# Generated by Django 6.0 on 2026-01-12 17:13

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_message_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Ф. И. О."),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("email", "owner")},
        ),
    ]
